apiVersion: v1
kind: Secret
metadata:
  name: {{ include "h3xinfra-keycloak-main.fullname" . }}-keycloak-admin
  labels:
    {{- include "h3xinfra-keycloak-main.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.admin.username | b64enc }}
  password: {{ .Values.secrets.admin.password | b64enc }}

