apiVersion: v1
kind: Secret
metadata:
  name: {{ include "h3xinfra-keycloak-main.fullname" . }}-postgresql-auth
  labels:
    {{- include "h3xinfra-keycloak-main.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.database.username | b64enc }}
  password: {{ .Values.secrets.database.password | b64enc }}
