apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "h3xinfra-certmanager-post.fullname" . }}-default-clusterissuer
  labels:
    {{- include "h3xinfra-certmanager-post.labels" . | nindent 4 }}
  {{- with .Values.clusterIssuer.annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{ include "h3xinfra-certmanager-post.fullname" . }}-default-clusterissuer-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: {{ include "h3xinfra-certmanager-post.fullname" . }}-cloudflare-api-token
            key: api-token
      selector:
        dnsZones: {{ with .Values.clusterIssuer.acme.dnsZones }}
          {{- toYaml . | nindent 8 }}
          {{- else }}
          {{ fail "No DNS zones specified for ClusterIssuer" }}
          {{- end }}

