---
- import_playbook: ../99-utils/kube-connect.yml

- name: Deploy Ingress-Nginx via Helm
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add Ingress-Nginx Helm repository
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
        state: present

    - name: Create Ingress-Nginx namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ ingressnginx.namespace }}"
        state: present
        wait: true

    - name: Deploy Ingress-Nginx configuration via Helm
      kubernetes.core.helm:
        name: "{{ ingressnginx.release_name_prefix }}-pre"
        chart_ref: "{{ playbook_dir }}/charts/h3xinfra-ingressnginx-pre"
        namespace: "{{ ingressnginx.namespace }}"
        create_namespace: false
        values:
          fullnameOverride: "{{ ingressnginx.release_name_prefix }}-pre"
          wildcardCertificate:
            commonName: "{{ ingressnginx.dns_names | first }}"
          clusterIssuerName: "{{ certmanager.release_name_prefix }}-post-default-clusterissuer"
          ipPool:
            namespace: "{{ metallb.namespace }}"
            ipAddressPools:
              addresses:
                ipv4: "{{ ingressnginx.loadbalancer_pools.ipv4 }}"
                ipv6: "{{ ingressnginx.loadbalancer_pools.ipv6 }}"
        set_values:
        - value: "wildcardCertificate.dnsNames={{ ingressnginx.dns_names | to_json }}"
          value_type: json
        state: present
        wait: true
        timeout: "120s"

    - name: Deploy Ingress-Nginx via Helm
      kubernetes.core.helm:
        name: "{{ ingressnginx.release_name_prefix }}-main"
        chart_ref: "ingress-nginx/ingress-nginx"
        chart_version: "{{ ingressnginx.chart_version }}"
        namespace: "{{ ingressnginx.namespace }}"
        create_namespace: false
        values: 
          controller:
            service:
              ipFamilies:
                - IPv4
                - IPv6
              ipFamilyPolicy: PreferDualStack
              annotations:
                metallb.universe.tf/address-pool: "{{ ingressnginx.release_name_prefix }}-pre-pool"
            extraArgs:
              default-ssl-certificate: "{{ ingressnginx.namespace }}/{{ ingressnginx.release_name_prefix }}-pre-wildcard-certificate"
            config:
              annotations-risk-level: "Critical"
            allowSnippetAnnotations: true

        state: present
        wait: true
        timeout: "120s"
        