---
- import_playbook: ../99-utils/kube-connect.yml

- name: Remove NGINX Ingress Controller via Helm
  hosts: k8s
  gather_facts: false

  tasks:
    - name: Uninstall Ingress-Nginx via Helm
      kubernetes.core.helm:
        name: "{{ ingressnginx.release_name_prefix }}-main"
        namespace: "{{ ingressnginx.namespace }}"
        state: absent
        wait: true
        timeout: "300s"

    - name: Uninstall Ingress-Nginx configuration via Helm
      kubernetes.core.helm:
        name: "{{ ingressnginx.release_name_prefix }}-pre"
        namespace: "{{ ingressnginx.namespace }}"
        state: absent
        wait: true
        timeout: "300s"

    - name: Remove Ingress-Nginx namespace
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ ingressnginx.namespace }}"
        wait: true
        wait_timeout: 300
