apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "h3xinfra-keycloak-main.fullname" . }}-postgresql

  labels:
    app: postgresql
    {{- include "h3xinfra-keycloak-main.labels" . | nindent 4 }}
  {{- with .Values.postgresql.deployment.annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      {{- include "h3xinfra-keycloak-main.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgresql
        {{- include "h3xinfra-keycloak-main.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: mirror.gcr.io/postgres:17
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "h3xinfra-keycloak-main.fullname" . }}-postgresql-auth
                  key: username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "h3xinfra-keycloak-main.fullname" . }}-postgresql-auth
                  key: password
                  optional: false
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_LOG_STATEMENT
              value: "all"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data

      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "h3xinfra-keycloak-main.fullname" . }}-postgresql
