---
- import_playbook: ../99-utils/kube-connect.yml

- name: Deploy Keycloak via Helm
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Keycloak namespace
      kubernetes.core.k8s:
        name: "{{ keycloak_namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        wait: true

    - name: Deploy Keycloak Helm chart
      kubernetes.core.helm:
        name: "{{ keycloak_release_name_prefix }}-main"
        chart_ref: "{{ playbook_dir }}/charts/h3xinfra-keycloak-main"
        release_namespace: "{{ keycloak_namespace }}"
        create_namespace: false
        wait: true
        values:
          fullnameOverride: "{{ keycloak_release_name_prefix }}-main"
          secrets:
            admin:
              enabled: true
              name: keycloak-preconfigured-admin
              username: "{{ keycloak_admin_username }}"
              password: "{{ keycloak_admin_password }}"
            database:
              enabled: true
              name: keycloak-db-secret
              username: "{{ keycloak_db_username }}"
              password: "{{ keycloak_db_password }}"

          keycloak:
            ingress:
              hostname: "{{ keycloak_ingress_hostname }}"
            certificate:
              enabled: true
              issuer: "{{ certmanager_release_name_prefix }}-post-default-clusterissuer"
        state: present
        wait: true
        timeout: "120s"

