---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/python3"
    k8s:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/python3"

k3s_cluster:
  children:
    server:
      hosts:
        node01.example.com:
          ansible_host: 192.168.1.10
          extra_server_args: "--node-ip=192.168.1.10,2001:db8::10"
        node02.example.com:
          ansible_host: 192.168.1.11
          extra_server_args: "--node-ip=192.168.1.11,2001:db8::11"
        node03.example.com:
          ansible_host: 192.168.1.12
          extra_server_args: "--node-ip=192.168.1.12,2001:db8::12"
    agent:
      hosts:
        worker01.example.com:
          ansible_host: 192.168.1.20
          extra_server_args: "--node-ip=192.168.1.20,2001:db8::20"
        worker02.example.com:
          ansible_host: 192.168.1.21
          extra_server_args: "--node-ip=192.168.1.21,2001:db8::21"
  vars:
    ansible_port: 22
    ansible_user: ansible
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"