---
# Vault-encrypted secrets (examples)
# Use ansible-vault to encrypt this file:
# ansible-vault encrypt inventory/production/group_vars/all/secrets.yml

# Example vault variables that would be encrypted:
k3s_token: "{{ vault_k3s_token }}"
storage_password: "{{ vault_storage_password }}"
dns_api_token: "{{ vault_dns_api_token }}"

# These vault variables would contain the actual encrypted values:
# vault_k3s_token: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   ...encrypted_content...
# vault_storage_password: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   ...encrypted_content...
# vault_dns_api_token: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   ...encrypted_content...