apiVersion: v1
kind: Secret
metadata:
  name: {{ include "h3xinfra-longhorn-pre.fullname" . }}-cifs-secret
type: Opaque
data:
  CIFS_USERNAME: {{ .Values.longhornCifsSecret.cifsUsername | b64enc | quote }}
  CIFS_PASSWORD: {{ .Values.longhornCifsSecret.cifsPassword | b64enc | quote }}
