apiVersion: v1
kind: Secret
metadata:
  name: {{ include "h3xinfra-longhorn-post.fullname" . }}-basic-auth-secret
type: Opaque
data:
  auth: {{ .Values.longhornBasicAuthSecret.auth | b64enc | quote }}
