apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "h3xinfra-longhorn-post.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "h3xinfra-longhorn-post.fullname" . }}-basic-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- if .Values.longhornIngress.trustedIPs }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.longhornIngress.trustedIPs | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.longhornIngress.host }}
  rules:
  - host: {{ .Values.longhornIngress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
