{{- if eq .Values.longhornIngress.auth.method "basic" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "h3xinfra-longhorn-post.fullname" . }}-basic-auth-secret
type: Opaque
data:
  auth: {{ .Values.longhornIngress.auth.basic.secret | b64enc | quote }}
{{- end }}