apiVersion: v1
kind: Secret
metadata:
  name: {{ include "h3xinfra-externaldns-pre.fullname" . }}-cloudflare-api-token
  labels:
    {{- include "h3xinfra-externaldns-pre.labels" . | nindent 4 }}
  {{- with .Values.cloudflareApiToken.annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  api-token: {{ with .Values.cloudflareApiToken.token | b64enc | quote }}
    {{- . | nindent 4 }}
  {{- else }}
    {{- fail "cloudflareApiToken.token is required" }}
  {{- end }}
