apiVersion: v1
kind: Service
metadata:
  name: {{ include "h3xinfra-keycloak-main.fullname" . }}-keycloak-discovery
  
  labels:
    app: keycloak
    {{- include "h3xinfra-keycloak-main.labels" . | nindent 4 }}
  {{- with .Values.keycloak.serviceDiscovery.annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: keycloak
    {{- include "h3xinfra-keycloak-main.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
  clusterIP: None
  type: ClusterIP
