apiVersion: v1
kind: Service
metadata:
  name: {{ include "h3xinfra-keycloak-main.fullname" . }}-keycloak

  labels:
    app: keycloak
    {{- include "h3xinfra-keycloak-main.labels" . | nindent 4 }}
  {{- with .Values.keycloak.service.annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: keycloak
    {{- include "h3xinfra-keycloak-main.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
    - protocol: TCP
      port: 8443
      targetPort: https
      name: https
  type: ClusterIP
